services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/darrenofficial/dpaste:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "8000"
